// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type EnergyMeasurement struct {
	RespondentCode string `json:"respondent_code"`
	RespondentName string `json:"respondent_name"`
	FuelTypeCode   string `json:"fuel_type_code"`
	FuelTypeName   string `json:"fuel_type_name"`
	ValueUnits     string `json:"value_units"`
	Value          int    `json:"value"`
}
